@startuml

package "Build pipeline" as 2 {
[init] as i1
[checkout]
[get-version]
[tests] as t1
[sonar] as s1
[build] as b1
[build-image-kaniko]
[create-jira-issue-metadata]
[ecr-to-docker]
[git-tag]

i1->[checkout]
[checkout]->[get-version]
[get-version]->t1
t1->s1
s1->b1
b1->[build-image-kaniko]
[build-image-kaniko]->[create-jira-issue-metadata]
[create-jira-issue-metadata]->[ecr-to-docker]
[ecr-to-docker]->[git-tag]
}


@enduml