@startuml

package "Deploy Pipeline" as 3 {
[init] as i2
[auto-deploy-input \nOR\nmanual-deploy-input] as deployInput
i2->deployInput
deployInput->[deploy]
[deploy]->[approve]
[approve]->[promote-images]
}
@enduml