FROM squidfunk/mkdocs-material:9.0.4

RUN pip install \
    fancyboxmd==1.1.0 \
    mdx-truly-sane-lists==1.3 \
    mkdocs-awesome-pages-plugin==2.8.0 \
    mkdocs-charts-plugin==0.0.8 \
    plantuml-markdown==3.8.0 \
    mike==1.1.2
