FROM squidfunk/mkdocs-material:8.2.8

RUN pip install \
    mdx-truly-sane-lists==1.2 \
    mkdocs-awesome-pages-plugin==2.6.1 \
    fancyboxmd==1.0.1 \
    mkdocs-charts-plugin==0.0.8 \
    plantuml-markdown==3.5.2
