FROM squidfunk/mkdocs-material:9.5.3

RUN pip install \
    fancyboxmd==1.1.0 \
    mdx-truly-sane-lists==1.3 \
    mike==2.0.0 \
    mkdocs-awesome-pages-plugin==2.9.0 \
    mkdocs-git-committers-plugin-2==2.2.2 \
    mkdocs-git-revision-date-localized-plugin==1.2.2 \
    mkdocs-meta-descriptions-plugin==2.3.0 \
    mkdocs-redirects==1.2.1 \
    mkdocs-video==1.5.0
