{{- if not (lookup "v2.edp.epam.com/v1alpha1" "Jenkins" ".Values.edp.name" "jenkins").metadata }}
apiVersion: v2.edp.epam.com/v1alpha1
kind: Jenkins
metadata:
  name: jenkins
spec:
  edpSpec:
    dnsWildcard: "{{ .Values.edp.dnsWildCard }}"
    {{- if .Values.jenkins.pullSecrets}}
    imagePullSecrets:
      {{- range .Values.jenkins.pullSecrets }}
      - {{. -}}
      {{- end -}}
    {{end}}
  image: "{{.Values.jenkins.image}}"
  version: {{.Values.jenkins.version}}
  volumes:
    - name: "data"
      storageClass: {{ if .Values.jenkins.storageClass }}"{{ .Values.jenkins.storageClass }}"{{else}}"gp2"{{end}}
      capacity: {{ if .Values.jenkins.volumeCapacity }}"{{ .Values.jenkins.volumeCapacity }}"{{else}}"10Gi"{{end}}
  sharedLibraries:
    - name: "edp-library-stages"
      id: "Stages"
      repository: {{ if .Values.jenkins.sharedLibraryRepo.stages }}"{{ .Values.jenkins.sharedLibraryRepo.stages }}"{{else}}"https://github.com/epmd-edp/edp-library-stages.git"{{end}}
      version: "{{ .Values.jenkins.sharedLibraryVersion.stages }}"
    - name: "edp-library-pipelines"
      id: "Pipelines"
      repository: {{ if .Values.jenkins.sharedLibraryRepo.pipelines }}"{{ .Values.jenkins.sharedLibraryRepo.pipelines }}"{{else}}"https://github.com/epmd-edp/edp-library-pipelines.git"{{end}}
      version: "{{ .Values.jenkins.sharedLibraryVersion.pipelines }}"
  keycloakSpec:
    enabled: true
    realm: "{{ .Values.edp.name }}-edp"
{{end}}