apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tenant-developer
rules:
  # Allow developers to create, update and delete applications
  # Since the platform use PipelineRuns for ArgoCD applications management, we also provide developers to directly create/update/delete ArgoCD applications
  - apiGroups:
      - argoproj.io
    resources:
      - applications
    verbs:
      - create
      - update
      - delete
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
      - taskruns
    verbs:
      - get
      - list
      - watch
      - create
  - apiGroups:
      - tekton.dev
    resources:
      - pipelines
      - tasks
    verbs:
      - get
      - list
      - watch
      - patch
      - create
      - update
      - delete
  - apiGroups:
      - triggers.tekton.dev
    resources:
      - interceptors
      - triggertemplates
      - eventlisteners
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - triggers.tekton.dev
    resources:
      - triggerbindings
      - triggers
    verbs:
      - get
      - list
      - watch
      - create
  - apiGroups:
      - ''
    resources:
      - configmaps
    verbs:
      - '*'
  - apiGroups:
      - edp.epam.com
    resources:
      - approvaltasks
    verbs:
      - update
  - apiGroups:
      - v2.edp.epam.com
    resources:
      - codebasebranches
    verbs:
      - '*'
  - apiGroups:
      - v2.edp.epam.com
    resources:
      - stages
      - cdpipelines
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
