apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tenant-developer
rules:
  # Allow developers to create, update and delete applications
  # Since the platform use PipelineRuns for ArgoCD applications management, we also provide developers to directly create/update/delete ArgoCD applications
  - apiGroups:
      - argoproj.io
    resources:
      - applications
    verbs:
      - create
      - update
      - delete
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
    verbs:
      - create
      - update
      - delete
