apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tenant-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: {{ .Values.global.viewerGroupName | default (printf "%s-oidc-viewers" .Release.Namespace) | quote }}
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: {{ .Values.global.developerGroupName | default (printf "%s-oidc-developers" .Release.Namespace) | quote }}
