apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tenant-developer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tenant-developer
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: "{{ .Values.global.edpName }}-oidc-developers"
