{{- if eq .Values.global.platform "openshift" -}}
apiVersion: authorization.openshift.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "edp-install.labels" . | nindent 4 }}
  name: edp-{{ .Values.global.edpName }}
roleRef:
  name: edp-{{ .Values.global.edpName }}
subjects:
- kind: ServiceAccount
  name: edp
  namespace: {{ .Values.global.edpName }}
userNames:
- system:serviceaccount:{{ .Values.global.edpName }}:edp
groupNames: []
{{- end -}}
