{{- if eq .Values.global.platform "openshift" -}}
  {{- if not (lookup "authorization.openshift.io/v1" "RoleBinding" .Values.global.edpName "developer").metadata}}
apiVersion: authorization.openshift.io/v1
groupNames:
  {{- range .Values.edp.developerGroups }}
  - {{. -}}
  {{end}}
kind: RoleBinding
metadata:
  name: developer
roleRef:
  name: view
subjects:
  {{- range .Values.edp.developerGroups }}
  - kind: Group
    name: {{. -}}
  {{end}}
userNames: []
  {{end}}
{{end}}