{{- if eq .Values.global.platform "openshift" -}}
apiVersion: authorization.openshift.io/v1
groupNames: null
kind: RoleBinding
metadata:
  labels:
    {{- include "edp-install.labels" . | nindent 4 }}
  name: edp-{{ .Release.Namespace }}
roleRef:
  name: edp-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: edp
  namespace: {{ .Release.Namespace }}
userNames:
- system:serviceaccount:{{ .Release.Namespace }}:edp
{{- end -}}
