apiVersion: v2
description: A Helm chart for EDP Install
home: https://epam.github.io/edp-install/
name: edp-install
type: application
version: 3.8.1
appVersion: 3.8.1
icon: https://epam.github.io/edp-install/assets/logo.png
keywords:
  - edp
  - install
  - application
  - pipelines
maintainers:
  - name: epmd-edp
    email: SupportEPMD-EDP@epam.com
    url: https://solutionshub.epam.com/solution/epam-delivery-platform
  - name: sergk
    url: https://github.com/SergK
sources:
  - https://github.com/epam/edp-install

dependencies:
- name: codebase-operator
  repository: "@epamedp"
  version: "2.22.1"
  condition: codebase-operator.enabled

- name: edp-headlamp
  repository: "@epamedp"
  version: "0.14.0"
  condition: edp-headlamp.enabled

- name: edp-tekton
  repository: "@epamedp"
  version: "0.11.0"
  condition: edp-tekton.enabled

- name: cd-pipeline-operator
  repository: "@epamedp"
  version: "2.19.0"
  condition: cd-pipeline-operator.enabled

- name: gerrit-operator
  repository: "@epamedp"
  version: "2.20.1"
  condition: gerrit-operator.enabled

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/operator: "true"
  artifacthub.io/operatorCapabilities: Full Lifecycle
  artifacthub.io/links: |
    - name: EDP Documentation
      url: https://epam.github.io/edp-install/
    - name: EPAM SolutionHub
      url: https://solutionshub.epam.com/solution/epam-delivery-platform
