apiVersion: v2
description: A Helm chart for EDP Install
home: https://solutionshub.epam.com/solution/epam-delivery-platform
name: edp-install
type: application
version: 2.10.0
appVersion: 2.10.0
maintainers:
  - name: EPAM EDP Team
sources:
  - https://github.com/epam/edp-install

dependencies:
- name: keycloak-operator
  repository: "@epamedp"
  version: "1.10.0"
  condition: keycloak-operator.enabled

- name: codebase-operator
  repository: "@epamedp"
  version: "2.10.0"
  condition: codebase-operator.enabled

- name: jenkins-operator
  repository: "@epamedp"
  version: "2.10.0"
  condition: jenkins-operator.enabled

- name: edp-component-operator
  repository: "@epamedp"
  version: "0.10.0"
  condition: edp-component-operator.enabled

- name: cd-pipeline-operator
  repository: "@epamedp"
  version: "2.10.0"
  condition: cd-pipeline-operator.enabled

- name: nexus-operator
  repository: "@epamedp"
  version: "2.10.0"
  condition: nexus-operator.enabled

- name: sonar-operator
  repository: "@epamedp"
  version: "2.10.2"
  condition: sonar-operator.enabled

- name: admin-console-operator
  repository: "@epamedp"
  version: "2.10.0"
  condition: admin-console-operator.enabled

- name: gerrit-operator
  repository: "@epamedp"
  version: "2.10.0"
  condition: gerrit-operator.enabled

- name: reconciler
  repository: "@epamedp"
  version: "2.10.0"
  condition: reconciler.enabled

- name: perf-operator
  repository: "@epamedp"
  version: "2.10.0"
  condition: perf-operator.enabled