apiVersion: v2
description: A Helm chart for EDP Install
home: https://solutionshub.epam.com/solution/epam-delivery-platform
name: edp-install
type: application
version: 2.8.4
appVersion: 2.8.4
maintainers:
  - name: EPAM EDP Team
sources:
  - https://github.com/epam/edp-install

dependencies:
- name: keycloak-operator
  repository: "@epamedp"
  version: "1.8.0"
  tags:
    - keycloak-operator

- name: codebase-operator
  repository: "@epamedp"
  version: "2.8.1"
  tags:
    - codebase-operator

- name: jenkins-operator
  repository: "@epamedp"
  version: "2.8.3"
  tags:
    - jenkins-operator

- name: edp-component-operator
  repository: "@epamedp"
  version: "0.8.0"
  tags:
    - edp-component-operator

- name: cd-pipeline-operator
  repository: "@epamedp"
  version: "2.8.2"
  tags:
    - cd-pipeline-operator

- name: nexus-operator
  repository: "@epamedp"
  version: "2.8.1"
  tags:
    - nexus-operator

- name: sonar-operator
  repository: "@epamedp"
  version: "2.8.0"
  tags:
    - sonar-operator

- name: admin-console-operator
  repository: "@epamedp"
  version: "2.8.2"
  tags:
    - admin-console-operator

- name: gerrit-operator
  repository: "@epamedp"
  version: "2.8.0"
  tags:
    - gerrit-operator

- name: reconciler
  repository: "@epamedp"
  version: "2.8.1"
  tags:
    - reconciler

- name: perf-operator
  repository: "@epamedp"
  version: "2.8.0"
  tags:
    - perf-operator
