apiVersion: v2
description: A Helm chart for EDP Install
home: https://epam.github.io/edp-install/
name: edp-install
type: application
version: 3.4.0
appVersion: 3.4.0
icon: https://epam.github.io/edp-install/assets/logo.png
keywords:
  - edp
  - install
  - application
  - pipelines
maintainers:
  - name: epmd-edp
    email: SupportEPMD-EDP@epam.com
    url: https://solutionshub.epam.com/solution/epam-delivery-platform
  - name: sergk
    url: https://github.com/SergK
sources:
  - https://github.com/epam/edp-install

dependencies:
- name: keycloak-operator
  repository: "@epamedp"
  version: "1.17.0"
  condition: keycloak-operator.enabled

- name: codebase-operator
  repository: "@epamedp"
  version: "2.17.0"
  condition: codebase-operator.enabled

- name: edp-component-operator
  repository: "@epamedp"
  version: "0.13.0"
  condition: edp-component-operator.enabled

- name: edp-headlamp
  repository: "@epamedp"
  version: "0.7.0"
  condition: edp-headlamp.enabled

- name: edp-tekton
  repository: "@epamedp"
  version: "0.6.0"
  condition: edp-tekton.enabled

- name: cd-pipeline-operator
  repository: "@epamedp"
  version: "2.15.0"
  condition: cd-pipeline-operator.enabled

- name: nexus-operator
  repository: "@epamedp"
  version: "2.16.0"
  condition: nexus-operator.enabled

- name: sonar-operator
  repository: "@epamedp"
  version: "2.14.1"
  condition: sonar-operator.enabled

- name: gerrit-operator
  repository: "@epamedp"
  version: "2.16.0"
  condition: gerrit-operator.enabled

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/operator: "true"
  artifacthub.io/images: |
    - name: keycloak-operator:1.17.0
      image: epamedp/keycloak-operator:1.17.0
    - name: codebase-operator:2.17.0
      image: epamedp/codebase-operator:2.17.0
    - name: cd-pipeline-operator:2.15.0
      image: epamedp/cd-pipeline-operator:2.15.0
    - name: nexus-operator:2.16.0
      image: epamedp/nexus-operator:2.16.0
    - name: sonar-operator:2.14.1
      image: epamedp/sonar-operator:2.14.1
    - name: gerrit-operator:2.16.0
      image: epamedp/gerrit-operator:2.16.0
    - name: edp-headlamp:0.7.0
      image: epamedp/edp-headlamp:0.7.0
    - name: postgres:9.6
      image: postgres:9.6
    - name: executor:v1.12.1-debug
      image: gcr.io/kaniko-project/executor:v1.12.1-debug
    - name: busybox:1.35.0
      image: busybox:1.35.0
    - name: aws-cli:2.9.4
      image: amazon/aws-cli:2.9.4
  artifacthub.io/operatorCapabilities: Full Lifecycle
  artifacthub.io/links: |
    - name: EDP Documentation
      url: https://epam.github.io/edp-install/
    - name: EPAM SolutionHub
      url: https://solutionshub.epam.com/solution/epam-delivery-platform
