apiVersion: v2
description: A Helm chart for KubeRocketCI Platform
home: https://docs.kuberocketci.io/
name: edp-install
type: application
version: 3.12.0
appVersion: 3.12.0
icon: https://docs.kuberocketci.io/img/logo.svg
keywords:
  - edp
  - install
  - application
  - pipelines
maintainers:
  - name: epmd-edp
    email: SupportEPMD-EDP@epam.com
    url: https://solutionshub.epam.com/solution/kuberocketci
  - name: sergk
    url: https://github.com/SergK
sources:
  - https://github.com/epam/edp-install

dependencies:
- name: codebase-operator
  repository: "@epamedp"
  version: "2.28.0"
  condition: codebase-operator.enabled

- name: edp-headlamp
  repository: "@epamedp"
  version: "0.23.0"
  condition: edp-headlamp.enabled

- name: edp-tekton
  repository: "@epamedp"
  version: "0.19.0"
  condition: edp-tekton.enabled

- name: cd-pipeline-operator
  repository: "@epamedp"
  version: "2.26.0"
  condition: cd-pipeline-operator.enabled

- name: gerrit-operator
  repository: "@epamedp"
  version: "2.24.0"
  condition: gerrit-operator.enabled

- name: gitfusion
  repository: "@epamedp"
  version: "0.1.1"
  condition: gitfusion.enabled

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/operator: "true"
  artifacthub.io/operatorCapabilities: Full Lifecycle
  artifacthub.io/links: |
    - name: KubeRocketCI Documentation
      url: https://docs.kuberocketci.io
    - name: EPAM SolutionHub
      url: https://solutionshub.epam.com/solution/kuberocketci
