apiVersion: v2
appVersion: 1.16.0
dependencies:
- name: keycloak-operator
  repository: '@epamedp'
  tags:
  - keycloak-operator
  version: v1.6.0
- name: codebase-operator
  repository: '@epamedp'
  tags:
  - codebase-operator
  version: v2.6.1
- name: jenkins-operator
  repository: '@epamedp'
  tags:
  - jenkins-operator
  version: v2.6.0
- name: edp-component-operator
  repository: '@epamedp'
  tags:
  - edp-component-operator
  version: v0.5.0
- name: cd-pipeline-operator
  repository: '@epamedp'
  tags:
  - cd-pipeline-operator
  version: v2.6.0
- name: nexus-operator
  repository: '@epamedp'
  tags:
  - nexus-operator
  version: v2.6.1
- name: sonar-operator
  repository: '@epamedp'
  tags:
  - sonar-operator
  version: v2.6.1
- name: admin-console-operator
  repository: '@epamedp'
  tags:
  - admin-console-operator
  version: v2.6.1
- name: gerrit-operator
  repository: '@epamedp'
  tags:
  - gerrit-operator
  version: v2.6.0
- name: reconciler
  repository: '@epamedp'
  tags:
  - reconciler
  version: v2.6.0
- name: perf-operator
  repository: '@epamedp'
  tags:
  - perf-operator
  version: v2.6.0
description: A Helm chart for Kubernetes
name: edp-install
type: application
version: 2.6.8
