global:
  gitProviders:
    - gitlab
  dnsWildCard:
  platform: openshift

  # Define the Image Registry that will be used in Pipelines.
  # This section is optional, and users can configure the registry within the EDP Portal user interface.
  #
  # Platform supports several types of registries, such as 'ecr', 'harbor', 'dockerhub' and 'openshift'.
  # 'openshift' registry is available only in case if platform is deployed on the OpenShift cluster and the variable global.platform is set to 'openshift'
  #
  # Below is an example of endpoint values for each registry type:
  # type:      | url
  # =============================
  # ecr        | <aws_account_id>.dkr.ecr.<aws_region>.amazonaws.com
  # harbor     | <registry.example.com>
  # dockerhub  | 'docker.io'
  # openshift  | <image-registry.openshift-image-registry.svc:5000>
  #
  # For example to integrate platform with dockerhub and publish image under 'my_user' account:
  # dockerRegistry:
  #   type: "dockerhub"
  #   url: "docker.io"
  #   space: "my_user"
  # As a result all image artifacts are published under https://hub.docker.com/repository/docker/my_user
  dockerRegistry:
    type: ""
    url: ""
    space: ""

externalSecrets:
  enabled: false

edp-headlamp:
  extraVolumes:
  - name: custom-ca
    secret:
      defaultMode: 420
      secretName: custom-ca-certificates

  # -- Additional volumeMounts to be added to the container
  extraVolumeMounts:
  - name: custom-ca
    mountPath: /etc/ssl/certs/ca.crt
    readOnly: true
    subPath: ca.crt
  config:
    oidc:
      enabled: true
      clientID: "client"

gerrit-operator:
  enabled: false
  gerrit:
    caCerts:
      # -- Flag for enabling additional CA certificates
      enabled: true
      # -- Change init CA certificates container image
      image: adoptopenjdk/openjdk11:alpine
      # -- Name of the secret containing additional CA certificates
      secret: custom-ca-certificates

edp-tekton:
  gitlab:
    host: gitlab.com

# -- Enable SSO for EDP components. Required keycloak-operator deployment. Default: false
sso:
  enabled: false
  # -- Keycloak URL
  keycloakUrl: https://keycloak.example.com
  # -- Administrators of your tenant
  admins:
    - "stub_user_one@example.com"
  # -- Developers of your tenant
  developers:
    - "stub_user_one@example.com"
    - "stub_user_two@example.com"

   # -- Additional volumes to be added to the OAuth2-proxy pod
  extraVolumes:
    - name: custom-ca
      secret:
        defaultMode: 420
        secretName: custom-ca

  # -- Additional volumeMounts to be added to the OAuth2-proxy container
  extraVolumeMounts:
    - name: custom-ca
      mountPath: /etc/ssl/certs/ca.crt
      readOnly: true
      subPath: ca.crt
