{{- if .Values.additionalTemplates.nexus.deploy -}}
  {{- if not (lookup "v2.edp.epam.com/v1alpha1" "Nexus" .Values.edp.name .Values.additionalTemplates.nexus.name).metadata }}
apiVersion: v2.edp.epam.com/v1alpha1
kind: Nexus
metadata:
  name: nexus
spec:
  edpSpec:
    dnsWildcard: {{ .Values.edp.dnsWildCard }}
  keycloakSpec:
    enabled: true
  users:
  {{- range .Values.edp.admins }}
  - email: ''
    first_name: ''
    last_name: ''
    roles:
      - nx-admin
    username: {{ . }}
  {{ end }}
  image: {{.Values.additionalTemplates.nexus.image}}
  version: {{.Values.additionalTemplates.nexus.image}}
  basePath: ""
  volumes:
    - capacity: 10Gi
      name: data
      storage_class: gp2
  {{end}}
{{end}}