@startuml
package "Code Review pipeline" as 1 {
[init] as i
[gerrit-checkout]
[commit-validate]
[build] as b
[tests] as t
package {
[sonar] as s
[lint]
}

i->[gerrit-checkout]
[gerrit-checkout]->[commit-validate]
[commit-validate]->b
b->t
t->s
s-[lint]
}

@enduml