{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.manageEDPInstallSecrets }}
{{- $secretStore := include "edp-install.secretStoreName" . }}
{{- $awsSecretName := .Values.externalSecrets.manageEDPInstallSecretsName }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ci-awx
spec:
  target:
    template:
      metadata:
        labels:
          app.edp.epam.com/secret-type: awx
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: {{ $secretStore }}
  data:
  - secretKey: username
    remoteRef:
      key: {{ $awsSecretName }}
      property: ci-awx.username
  - secretKey: password
    remoteRef:
      key: {{ $awsSecretName }}
      property: ci-awx.password
  - secretKey: url
    remoteRef:
      key: {{ $awsSecretName }}
      property: ci-awx.url
{{- end }}
