{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.manageEDPInstallSecrets -}}
{{- $secretStore := include "edp-install.secretStoreName" . }}
{{- $awsSecretName := .Values.externalSecrets.manageEDPInstallSecretsName }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ci-codemie
spec:
  target:
    template:
      metadata:
        labels:
          app.edp.epam.com/secret-type: codemie
          app.edp.epam.com/integration-secret: "true"
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: {{ $secretStore }}
  data:
  - secretKey: apiUrl
    remoteRef:
      key: {{ $awsSecretName }}
      property: ci-codemie.apiUrl
  - secretKey: assistantId
    remoteRef:
      key: {{ $awsSecretName }}
      property: ci-codemie.assistantId
  - secretKey: token
    remoteRef:
      key: {{ $awsSecretName }}
      property: ci-codemie.token
{{- end }}
