{{- if .Values.externalSecrets.enabled }}
{{- if eq .Values.externalSecrets.type "generic" }}
apiVersion: {{ include "app.externalSecrets.apiVersion" . }}
kind: SecretStore
metadata:
  name: {{ include "edp-install.secretStoreName" . }}
  labels:
    {{- include "edp-install.labels" . | nindent 4 }}
spec:
  provider:
    {{- with .Values.externalSecrets.secretProvider.generic.secretStore.providerConfig }}
      {{-  toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
{{- end }}
