kind: ServiceAccount
apiVersion: v1
metadata:
  name: edp-kaniko
  namespace: {{ .Values.global.edpName }}
  {{- if .Values.kanikoRoleArn  }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.kanikoRoleArn }}
  {{ end }}