apiVersion: v1.edp.epam.com/v1
kind: KeycloakClientScope
metadata:
  name: edp
  labels:
    {{- include "edp-install.labels" . | nindent 4 }}
spec:
  name: edp
  realm: main
  description: "default edp scope required for admin console, nexus and oauth2-proxy"
  protocol: openid-connect
  protocolMappers:
    - name: nexus-audience
      protocol: openid-connect
      protocolMapper: "oidc-audience-mapper"
      config:
        "access.token.claim": "true"
        "included.client.audience": "nexus"
    - name: admin-console-client-audience
      protocol: openid-connect
      protocolMapper: "oidc-audience-mapper"
      config:
        "access.token.claim": "true"
        "included.client.audience": "admin-console-client"
    - name: oauth2-proxy-audience
      protocol: openid-connect
      protocolMapper: "oidc-audience-mapper"
      config:
        "access.token.claim": "true"
        "included.client.audience": "oauth2-proxy"
