{{- if and .Values.sso.enabled .Values.sso.keycloakOperatorResources.createKeycloakCR }}
apiVersion: v1.edp.epam.com/v1
kind: Keycloak
metadata:
  name: {{ .Values.sso.keycloakOperatorResources.name }}
  labels:
    {{- include "edp-install.labels" . | nindent 4 }}
spec:
  url: {{ .Values.sso.keycloakUrl }}
  secret: "keycloak"
{{ end }}
