{{- if .Values.sso.enabled -}}
apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealm
metadata:
  name: "main"
  labels:
    {{- include "edp-install.labels" . | nindent 4 }}
spec:
  keycloakRef:
    kind: {{ .Values.sso.keycloakOperatorResources.kind }}
    name: {{ .Values.sso.keycloakOperatorResources.name }}
  realmName: {{ default .Release.Namespace .Values.sso.realmName }}
  browserFlow: browsers
{{- end }}
