apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealm
metadata:
  name: "main"
  labels:
    {{- include "edp-install.labels" . | nindent 4 }}
spec:
  keycloakOwner: main
  realmName: {{ .Values.global.edpName }}-main
  ssoRealmEnabled: true
  ssoRealmName: openshift
  users:
  {{- range .Values.global.admins }}
  - username: {{.}}
    realmRoles:
      - administrator
  {{- end}}
  {{- range .Values.global.developers }}
  - username: {{.}}
    realmRoles:
      - developer
  {{- end}}
